# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.9
        environment:
          MIX_ENV: test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
      - run: mix do deps.get, deps.compile

      - save_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
          paths:
            - deps
            - ~/.mix
            - _build
      - run: mix compile --warnings-as-errors
      - run: echo "$OTP_VERSION $ELIXIR_VERSION" > .version_file

      - restore_cache:
          keys:
            - plt-cache-{{ checksum ".version_file" }}-{{ checksum "mix.lock" }}
      - run: MIX_ENV=dev mix dialyzer --plt

      - save_cache:
          key: plt-cache-{{ checksum ".version_file"  }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - run: MIX_ENV=dev mix dialyzer --halt-exit-status
      - run: mix test
      - run: mix format --check-formatted
